a = Node(edges=[b])
b = Node(edges=[c, d])
c = Node(edges=[e, f, g])
d = Node(edges=[e, h, j])
e = Node(edges=[f])
f = Node(edges=[]) # same as Node()
g = Node()
h = Node(edges=[g])
j = Node(edges=[f])